@startuml

class Window {
-WindowManager mWindowManager
- String privateVal;
+ String publicVal;
--一种分割线--
==分割线==
- void getString();
+ void getStrigns();
}
class WindowManager
WindowManager <-- Window:关联关系(只是有关系)

class Company
class Department
Company o-- Department:聚合关系(耦合度相对组合偏低的依赖关系，两者生命周期可以不同)

class Bird
class Wing
Bird *-- Wing:组合关系(耦合度更高的关联关系，两者会具有相同的生命周期)

abstract class Factory
class CarFactory
Factory <|-- CarFactory:泛化关系，也就是继承关系

interface IColorDraw{
    draw()
}
class RedColorDraw{
    draw()
}
IColorDraw <|.. RedColorDraw:实现关系

class ImageLoader{
    loadImage(ImageInfo)
}
class ImageInfo{
}
ImageInfo <.. ImageLoader :依赖关系

enum currency{
 USD, CND
}

@enduml
