@startuml
actor actor1
agent agent1
artifact artifact1
cloud cloud1
component component1
package package1
folder folder1
file file1
node node1
frame frame1
collections collections1
card card1
database database1
storage storage1
interface  interface1
entity entity1
queue queue1
stack stack1
rectangle rectangle1
boundary boundary1
control control1
usecase usecase1
@enduml
