@startuml
title get(key)方法

start
:步骤1;
note left: 注解1
#HotPink: 步骤1-1;
#AAAAAA: 步骤1-2;
: 步骤2\n换行;
note right
  This note is on several
  这个是 //斜体//
  这个是 <b>粗体</b>
  ====
  * Calling the method ""foo()"" is prohibited
end note
 if(条件判断) then (为true时的注解)
       : __流程3有下划线__;
       partition 子模块1 {
          if(条件判断) then (为true时的注解)
            partition 子模块12{
                :流程4;
                note left: 流程4注解
                if(条件判断) then (为true时的注解)
                   -[#blue]-> 这个是注解,可以没有(->就结束);
                   : 流程5;
                else
                   partition 子模块123 {
                                    :流程1;
                                    :流程2;
                                    :流程3;
                                  }
                endif
             }
            partition 子模块13{
                    :流程1;
                    -[#green,dashed]-> The text can also be on several lines and **very** long;
                    :流程2;
                    while (循环条件)
                     :read data;
                     :generate diagrams;
                    endwhile
                    :流程3;
            }
          else
            :步骤5;
            repeat
              :read data;
              :generate diagrams;
            repeat while (循环条件)

            stop
          endif
       }
 else (false时的注解)
    : 流程3（valueReference）;
    note right: 注解3
    : 流程4;
    if (多线程并行处理?) then (true时的注解)
      fork
        :Treatment 1;
      fork again
        :Treatment 2;
      end fork
    else (false时的注解)
      :Treatment 1;
      :Treatment 2;
    endif
 endif
stop
@enduml