@startuml
actor actor1
agent agent1
artifact artifact1
boundary boundary1
card card1
cloud cloud1
component component1
control control1
database database1
entity entity1
file file1
folder folder1
frame frame1
interface  interface1
node node1
package package1
queue queue1
stack stack1
rectangle rectangle1
storage storage1
usecase usecase1




node Foo1 {
 cloud Foo2
}

cloud Foo3 {
  frame Foo4
}

database Foo5  {
  storage Foo6
}

storage Foo7 {
  storage Foo8
}
@enduml