@startuml
:开始;
:步骤1 |
:步骤2;
split
 :分枝1-1 <
 :分枝1-2 >
split again
 :分枝2-1 <
 :分枝2-2|
 :分枝2-3 ]
 :分枝2-4 >
split again
 :分枝3-1<
 :分枝3-2>
split again
 :分枝4 /
split again
 :分枝5 }
 stop
end split
:finish;
@enduml