@startmindmap
* upstream流程
** 初始化
** 初始化请求
***_ 调用create_request 回调函数进行构造发往上游服务器的请求
** 建立到上游服务器的连接
***_ 建立非阻塞套接字socket
***_ 设置写回调函数
***_ 设置读回调函数
** 上游服务器出错后，连接另一台服务器
** 发送请求到上游服务器
** 接收响应信息
@endmindmap