@startmindmap
* http请求流程
** 连接建立初始化
***_ 分配空间
***_ 设置读事件handler
***_ 添加读事件到定时器中
** 处理连接的可读事件
***_ 创建初始化接收缓存区
***_ 开始接收数据
***_ 创建请求结构体
***_ 设置读事件handler
** 处理请求行
** 处理请求头
** 处理请求
***_ 重新设置读写事件handler
***_ 处理各个模块的handler事件
****_ 处理http请求11个阶段
***_ 处理post请求
** 接收请求包体
** 发送响应头
** 发送响应包体
@endmindmap